### ISSUE TITLE
Diff hangs when comparing sequences with `nil`

### ISSUE THREAD

**Issue by pithyless** [droitfintech/clj-diff#3]
I've submitted an issue (https://github.com/brentonashworth/clj-diff/issues/9) and PR (https://github.com/brentonashworth/clj-diff/pull/8) to upstream, but considering the repo has not been updated in 8 years - perhaps @frenata could merge this and cut a new release?

Releasing a new version should fix https://github.com/lambdaisland/deep-diff/issues/6.

**Comment by frenata** [comment]
I'm very open to this -- we forked the library rather than vendor it so that we could fix some issues and contribute back.

**Comment by pithyless** [comment]
@frenata I've submitted PR https://github.com/droitfintech/clj-diff/pull/4.

Let me know if there is anything more you need from my end.

**Comment by frenata** [comment]
Merged and released `1.0.1` with the change, thanks.

**Comment by pithyless** [comment]
Awesome, thanks for the fast turnaround @frenata!
